events { 
    worker_connections 1024; 
}

http {
    # Define o formato dos logs de acesso (Crucial para AppSec auditar tráfego e ataques)
    log_format appsec_logs '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent"';

    access_log /var/log/nginx/access.log appsec_logs;

    # Configuração do Servidor Proxy
    server {
        listen 80; # O Nginx escuta na porta 80 INTERNA do contêiner
        server_name localhost;

        # Regra de Roteamento para o Microsserviço de Catálogo
        location /api/produtos {
            # Redireciona o tráfego para o contêiner do catálogo usando a rede interna do Docker.
            # O nome 'svc-catalogo' é o nome do contêiner que definiremos no docker-compose.
            proxy_pass http://svc-catalogo:5001/api/produtos;
            
            # Cabeçalhos AppSec: Preserva o IP real do cliente para o back-end conseguir logar corretamente
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Rota de monitoramento do próprio Gateway
        location /stub_status {
            stub_status on;
            allow 127.0.0.1;
            deny all;
        }
    }
}
